export type ScoreBand = 'low' | 'moderate' | 'high' | 'severe';
export type TransitionBand = 'leader' | 'advancing' | 'mixed' | 'lagging';
export type ReputationBand = 'strong' | 'stable' | 'mixed' | 'weak';
export type ControversyLevel = 'none' | 'minor' | 'moderate' | 'major';
export type NewsSentiment = 'positive' | 'steady' | 'negative';

export type DashboardCompany = {
  id: string;
  name: string;
  ticker: string;
  sector: string;
  industry: string;
  logoUrl: string;
  logoFallback: string;
  brandColor: string;
  carbonIntensityBand: ScoreBand;
  renewableTransitionBand: TransitionBand;
  laborBand: ReputationBand;
  privacyBand: ReputationBand;
  governanceBand: ReputationBand;
  controversy: ControversyLevel;
  newsSentiment: NewsSentiment;
};

const dashboardBlueChipUniverseSource: DashboardCompany[] = [
  { id: 'apple', name: 'Apple', ticker: 'AAPL', sector: 'Technology', industry: 'Consumer Hardware', logoUrl: 'https://cdn.simpleicons.org/apple/111111', logoFallback: 'AAPL', brandColor: '#9ca3af', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'microsoft', name: 'Microsoft', ticker: 'MSFT', sector: 'Technology', industry: 'Cloud Software', logoUrl: 'https://cdn.simpleicons.org/microsoft/5E5E5E', logoFallback: 'MSFT', brandColor: '#5E5E5E', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'nvidia', name: 'NVIDIA', ticker: 'NVDA', sector: 'Technology', industry: 'Semiconductors', logoUrl: 'https://cdn.simpleicons.org/nvidia/76B900', logoFallback: 'NVDA', brandColor: '#76B900', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'positive' },
  { id: 'amazon', name: 'Amazon', ticker: 'AMZN', sector: 'Consumer', industry: 'Internet Platforms', logoUrl: 'https://cdn.simpleicons.org/amazon/FF9900', logoFallback: 'AMZN', brandColor: '#FF9900', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'moderate', newsSentiment: 'steady' },
  { id: 'alphabet', name: 'Alphabet', ticker: 'GOOGL', sector: 'Technology', industry: 'Internet Services', logoUrl: 'https://cdn.simpleicons.org/google/4285F4', logoFallback: 'GOOG', brandColor: '#4285F4', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'mixed', governanceBand: 'strong', controversy: 'moderate', newsSentiment: 'steady' },
  { id: 'meta', name: 'Meta', ticker: 'META', sector: 'Technology', industry: 'Social Platforms', logoUrl: 'https://cdn.simpleicons.org/meta/0467DF', logoFallback: 'META', brandColor: '#0467DF', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'mixed', privacyBand: 'weak', governanceBand: 'mixed', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'netflix', name: 'Netflix', ticker: 'NFLX', sector: 'Communication Services', industry: 'Streaming Media', logoUrl: 'https://cdn.simpleicons.org/netflix/E50914', logoFallback: 'NFLX', brandColor: '#E50914', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'tesla', name: 'Tesla', ticker: 'TSLA', sector: 'Consumer', industry: 'Electric Vehicles', logoUrl: 'https://cdn.simpleicons.org/tesla/CC0000', logoFallback: 'TSLA', brandColor: '#CC0000', carbonIntensityBand: 'high', renewableTransitionBand: 'leader', laborBand: 'weak', privacyBand: 'mixed', governanceBand: 'weak', controversy: 'major', newsSentiment: 'negative' },
  { id: 'oracle', name: 'Oracle', ticker: 'ORCL', sector: 'Technology', industry: 'Enterprise Software', logoUrl: 'https://cdn.simpleicons.org/oracle/F80000', logoFallback: 'ORCL', brandColor: '#F80000', carbonIntensityBand: 'low', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'salesforce', name: 'Salesforce', ticker: 'CRM', sector: 'Technology', industry: 'Enterprise Software', logoUrl: 'https://cdn.simpleicons.org/salesforce/00A1E0', logoFallback: 'CRM', brandColor: '#00A1E0', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'positive' },
  { id: 'sap', name: 'SAP', ticker: 'SAP', sector: 'Technology', industry: 'Enterprise Software', logoUrl: 'https://cdn.simpleicons.org/sap/0FAAFF', logoFallback: 'SAP', brandColor: '#0FAAFF', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'ibm', name: 'IBM', ticker: 'IBM', sector: 'Technology', industry: 'IT Services', logoUrl: 'https://cdn.simpleicons.org/ibm/1261FE', logoFallback: 'IBM', brandColor: '#1261FE', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'tsmc', name: 'TSMC', ticker: 'TSM', sector: 'Technology', industry: 'Semiconductors', logoUrl: 'https://cdn.simpleicons.org/tsmc/CC0000', logoFallback: 'TSM', brandColor: '#CC0000', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'asml', name: 'ASML', ticker: 'ASML', sector: 'Technology', industry: 'Semiconductor Equipment', logoUrl: 'https://cdn.simpleicons.org/asml/0A214A', logoFallback: 'ASML', brandColor: '#0A214A', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'samsung', name: 'Samsung Electronics', ticker: '005930', sector: 'Technology', industry: 'Consumer Electronics', logoUrl: 'https://cdn.simpleicons.org/samsung/1428A0', logoFallback: 'SMSG', brandColor: '#1428A0', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'sony', name: 'Sony', ticker: 'SONY', sector: 'Consumer', industry: 'Electronics & Media', logoUrl: 'https://cdn.simpleicons.org/sony/FFFFFF', logoFallback: 'SONY', brandColor: '#6b7280', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'alibaba', name: 'Alibaba', ticker: 'BABA', sector: 'Consumer', industry: 'E-Commerce', logoUrl: 'https://cdn.simpleicons.org/alibabadotcom/FF6A00', logoFallback: 'BABA', brandColor: '#FF6A00', carbonIntensityBand: 'high', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'weak', governanceBand: 'mixed', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'tencent', name: 'Tencent', ticker: 'TCEHY', sector: 'Communication Services', industry: 'Internet Services', logoUrl: 'https://cdn.simpleicons.org/tencentqq/12B7F5', logoFallback: 'TCE', brandColor: '#12B7F5', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'siemens', name: 'Siemens', ticker: 'SIE', sector: 'Industrials', industry: 'Electrification', logoUrl: 'https://cdn.simpleicons.org/siemens/009999', logoFallback: 'SIE', brandColor: '#009999', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'airbus', name: 'Airbus', ticker: 'AIR', sector: 'Industrials', industry: 'Aerospace', logoUrl: 'https://cdn.simpleicons.org/airbus/00205B', logoFallback: 'AIR', brandColor: '#00205B', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'schneider-electric', name: 'Schneider Electric', ticker: 'SU', sector: 'Industrials', industry: 'Electrical Equipment', logoUrl: 'https://cdn.simpleicons.org/schneiderelectric/3DCD58', logoFallback: 'SU', brandColor: '#3DCD58', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'honeywell', name: 'Honeywell', ticker: 'HON', sector: 'Industrials', industry: 'Automation', logoUrl: 'https://cdn.simpleicons.org/honeywell/DD0031', logoFallback: 'HON', brandColor: '#DD0031', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'caterpillar', name: 'Caterpillar', ticker: 'CAT', sector: 'Industrials', industry: 'Heavy Equipment', logoUrl: 'https://cdn.simpleicons.org/caterpillar/FFCD11', logoFallback: 'CAT', brandColor: '#FFCD11', carbonIntensityBand: 'severe', renewableTransitionBand: 'lagging', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'negative' },
  { id: 'toyota', name: 'Toyota', ticker: 'TM', sector: 'Consumer', industry: 'Automotive', logoUrl: 'https://cdn.simpleicons.org/toyota/EB0A1E', logoFallback: 'TM', brandColor: '#EB0A1E', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'byd', name: 'BYD', ticker: 'BYDDY', sector: 'Consumer', industry: 'Electric Vehicles', logoUrl: 'https://cdn.simpleicons.org/bydauto/D0021B', logoFallback: 'BYD', brandColor: '#D0021B', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'mixed', controversy: 'minor', newsSentiment: 'positive' },
  { id: 'shell', name: 'Shell', ticker: 'SHEL', sector: 'Energy', industry: 'Oil & Gas', logoUrl: 'https://cdn.simpleicons.org/shell/FFD500', logoFallback: 'SHEL', brandColor: '#FFD500', carbonIntensityBand: 'severe', renewableTransitionBand: 'lagging', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'major', newsSentiment: 'negative' },
  { id: 'bp', name: 'BP', ticker: 'BP', sector: 'Energy', industry: 'Oil & Gas', logoUrl: 'https://cdn.simpleicons.org/bp/00A650', logoFallback: 'BP', brandColor: '#00A650', carbonIntensityBand: 'severe', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'major', newsSentiment: 'negative' },
  { id: 'totalenergies', name: 'TotalEnergies', ticker: 'TTE', sector: 'Energy', industry: 'Integrated Energy', logoUrl: 'https://cdn.simpleicons.org/totalenergies/FF4F00', logoFallback: 'TTE', brandColor: '#FF4F00', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'nextera', name: 'NextEra Energy', ticker: 'NEE', sector: 'Utilities', industry: 'Renewable Utilities', logoUrl: 'https://logo.clearbit.com/nexteraenergy.com', logoFallback: 'NEE', brandColor: '#00B388', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'enel', name: 'Enel', ticker: 'ENEL', sector: 'Utilities', industry: 'Integrated Utilities', logoUrl: 'https://cdn.simpleicons.org/enel/FC4C02', logoFallback: 'ENEL', brandColor: '#FC4C02', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'jpmorgan', name: 'JPMorgan Chase', ticker: 'JPM', sector: 'Financials', industry: 'Banking', logoUrl: 'https://cdn.simpleicons.org/jpmorganchase/FFFFFF', logoFallback: 'JPM', brandColor: '#94a3b8', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'mixed', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'goldman-sachs', name: 'Goldman Sachs', ticker: 'GS', sector: 'Financials', industry: 'Investment Banking', logoUrl: 'https://cdn.simpleicons.org/goldmansachs/7399C6', logoFallback: 'GS', brandColor: '#7399C6', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'bank-of-america', name: 'Bank of America', ticker: 'BAC', sector: 'Financials', industry: 'Banking', logoUrl: 'https://cdn.simpleicons.org/bankofamerica/012169', logoFallback: 'BAC', brandColor: '#012169', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'hsbc', name: 'HSBC', ticker: 'HSBC', sector: 'Financials', industry: 'Banking', logoUrl: 'https://cdn.simpleicons.org/hsbc/DB0011', logoFallback: 'HSBC', brandColor: '#DB0011', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'ubs', name: 'UBS', ticker: 'UBS', sector: 'Financials', industry: 'Wealth Management', logoUrl: 'https://cdn.simpleicons.org/ubs/E60000', logoFallback: 'UBS', brandColor: '#E60000', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'visa', name: 'Visa', ticker: 'V', sector: 'Financials', industry: 'Payments', logoUrl: 'https://cdn.simpleicons.org/visa/1A1F71', logoFallback: 'V', brandColor: '#1A1F71', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'mastercard', name: 'Mastercard', ticker: 'MA', sector: 'Financials', industry: 'Payments', logoUrl: 'https://cdn.simpleicons.org/mastercard/EB001B', logoFallback: 'MA', brandColor: '#EB001B', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'american-express', name: 'American Express', ticker: 'AXP', sector: 'Financials', industry: 'Payments', logoUrl: 'https://cdn.simpleicons.org/americanexpress/2E77BC', logoFallback: 'AXP', brandColor: '#2E77BC', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'berkshire-hathaway', name: 'Berkshire Hathaway', ticker: 'BRK.B', sector: 'Financials', industry: 'Diversified Holdings', logoUrl: 'https://logo.clearbit.com/berkshirehathaway.com', logoFallback: 'BRK', brandColor: '#94a3b8', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'blackrock', name: 'BlackRock', ticker: 'BLK', sector: 'Financials', industry: 'Asset Management', logoUrl: 'https://cdn.simpleicons.org/blackrock/FFFFFF', logoFallback: 'BLK', brandColor: '#94a3b8', carbonIntensityBand: 'low', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'novo-nordisk', name: 'Novo Nordisk', ticker: 'NVO', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://cdn.simpleicons.org/novonordisk/001965', logoFallback: 'NVO', brandColor: '#001965', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'roche', name: 'Roche', ticker: 'ROG', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://cdn.simpleicons.org/roche/0D2A5C', logoFallback: 'ROG', brandColor: '#0D2A5C', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'johnson-johnson', name: 'Johnson & Johnson', ticker: 'JNJ', sector: 'Healthcare', industry: 'Healthcare Products', logoUrl: 'https://logo.clearbit.com/jnj.com', logoFallback: 'JNJ', brandColor: '#D71920', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'pfizer', name: 'Pfizer', ticker: 'PFE', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://cdn.simpleicons.org/pfizer/0093D0', logoFallback: 'PFE', brandColor: '#0093D0', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'nestle', name: 'Nestle', ticker: 'NSRGY', sector: 'Consumer Staples', industry: 'Food & Beverage', logoUrl: 'https://logo.clearbit.com/nestle.com', logoFallback: 'NES', brandColor: '#6b7280', carbonIntensityBand: 'low', renewableTransitionBand: 'advancing', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'unilever', name: 'Unilever', ticker: 'UL', sector: 'Consumer Staples', industry: 'Household Products', logoUrl: 'https://cdn.simpleicons.org/unilever/1F36C7', logoFallback: 'UL', brandColor: '#1F36C7', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'procter-gamble', name: 'Procter & Gamble', ticker: 'PG', sector: 'Consumer Staples', industry: 'Household Products', logoUrl: 'https://logo.clearbit.com/pg.com', logoFallback: 'PG', brandColor: '#1D4ED8', carbonIntensityBand: 'low', renewableTransitionBand: 'advancing', laborBand: 'strong', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'pepsico', name: 'PepsiCo', ticker: 'PEP', sector: 'Consumer Staples', industry: 'Food & Beverage', logoUrl: 'https://cdn.simpleicons.org/pepsico/2151A1', logoFallback: 'PEP', brandColor: '#2151A1', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'coca-cola', name: 'Coca-Cola', ticker: 'KO', sector: 'Consumer Staples', industry: 'Beverages', logoUrl: 'https://cdn.simpleicons.org/cocacola/D00013', logoFallback: 'KO', brandColor: '#D00013', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'lvmh', name: 'LVMH', ticker: 'MC', sector: 'Consumer', industry: 'Luxury Goods', logoUrl: 'https://logo.clearbit.com/lvmh.com', logoFallback: 'LVMH', brandColor: '#cbd5e1', carbonIntensityBand: 'moderate', renewableTransitionBand: 'mixed', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'adyen', name: 'Adyen', ticker: 'ADYEN', sector: 'Financials', industry: 'Payments Infrastructure', logoUrl: 'https://cdn.simpleicons.org/adyen/0ABF53', logoFallback: 'ADY', brandColor: '#0ABF53', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'accenture', name: 'Accenture', ticker: 'ACN', sector: 'Technology', industry: 'Consulting', logoUrl: 'https://cdn.simpleicons.org/accenture/A100FF', logoFallback: 'ACN', brandColor: '#A100FF', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'cisco', name: 'Cisco', ticker: 'CSCO', sector: 'Technology', industry: 'Networking', logoUrl: 'https://cdn.simpleicons.org/cisco/1BA0D7', logoFallback: 'CSCO', brandColor: '#1BA0D7', carbonIntensityBand: 'low', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'broadcom', name: 'Broadcom', ticker: 'AVGO', sector: 'Technology', industry: 'Semiconductors', logoUrl: 'https://logo.clearbit.com/broadcom.com', logoFallback: 'AVGO', brandColor: '#CC092F', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'positive' },
  { id: 'intel', name: 'Intel', ticker: 'INTC', sector: 'Technology', industry: 'Semiconductors', logoUrl: 'https://cdn.simpleicons.org/intel/0071C5', logoFallback: 'INTC', brandColor: '#0071C5', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'steady' },
  { id: 'qualcomm', name: 'Qualcomm', ticker: 'QCOM', sector: 'Technology', industry: 'Semiconductors', logoUrl: 'https://cdn.simpleicons.org/qualcomm/3253DC', logoFallback: 'QCOM', brandColor: '#3253DC', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'servicenow', name: 'ServiceNow', ticker: 'NOW', sector: 'Technology', industry: 'Workflow Software', logoUrl: 'https://cdn.simpleicons.org/servicenow/81B441', logoFallback: 'NOW', brandColor: '#81B441', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'snowflake', name: 'Snowflake', ticker: 'SNOW', sector: 'Technology', industry: 'Cloud Data Platforms', logoUrl: 'https://cdn.simpleicons.org/snowflake/29B5E8', logoFallback: 'SNOW', brandColor: '#29B5E8', carbonIntensityBand: 'low', renewableTransitionBand: 'leader', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'abb', name: 'ABB', ticker: 'ABB', sector: 'Industrials', industry: 'Industrial Automation', logoUrl: 'https://cdn.simpleicons.org/abb/FF000F', logoFallback: 'ABB', brandColor: '#FF000F', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'stable', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'deere', name: 'Deere & Company', ticker: 'DE', sector: 'Industrials', industry: 'Machinery', logoUrl: 'https://logo.clearbit.com/deere.com', logoFallback: 'DE', brandColor: '#367C2B', carbonIntensityBand: 'high', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'rio-tinto', name: 'Rio Tinto', ticker: 'RIO', sector: 'Materials', industry: 'Mining', logoUrl: 'https://logo.clearbit.com/riotinto.com', logoFallback: 'RIO', brandColor: '#E31E24', carbonIntensityBand: 'severe', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'stable', governanceBand: 'stable', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'bhp', name: 'BHP', ticker: 'BHP', sector: 'Materials', industry: 'Mining', logoUrl: 'https://logo.clearbit.com/bhp.com', logoFallback: 'BHP', brandColor: '#FFB81C', carbonIntensityBand: 'severe', renewableTransitionBand: 'mixed', laborBand: 'mixed', privacyBand: 'stable', governanceBand: 'strong', controversy: 'moderate', newsSentiment: 'negative' },
  { id: 'linde', name: 'Linde', ticker: 'LIN', sector: 'Materials', industry: 'Industrial Gases', logoUrl: 'https://logo.clearbit.com/linde.com', logoFallback: 'LIN', brandColor: '#005591', carbonIntensityBand: 'high', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'stable', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'suncor', name: 'Suncor Energy', ticker: 'SU', sector: 'Energy', industry: 'Oil Sands', logoUrl: 'https://logo.clearbit.com/suncor.com', logoFallback: 'SU', brandColor: '#E87722', carbonIntensityBand: 'severe', renewableTransitionBand: 'lagging', laborBand: 'mixed', privacyBand: 'mixed', governanceBand: 'stable', controversy: 'major', newsSentiment: 'negative' },
  { id: 'novartis', name: 'Novartis', ticker: 'NVS', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://cdn.simpleicons.org/novartis/F66A3B', logoFallback: 'NVS', brandColor: '#F66A3B', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'merck', name: 'Merck', ticker: 'MRK', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://logo.clearbit.com/merck.com', logoFallback: 'MRK', brandColor: '#007A73', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'strong', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'sanofi', name: 'Sanofi', ticker: 'SNY', sector: 'Healthcare', industry: 'Pharmaceuticals', logoUrl: 'https://cdn.simpleicons.org/sanofi/00A3E0', logoFallback: 'SNY', brandColor: '#00A3E0', carbonIntensityBand: 'moderate', renewableTransitionBand: 'leader', laborBand: 'strong', privacyBand: 'strong', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
  { id: 'telefonica', name: 'Telefonica', ticker: 'TEF', sector: 'Communication Services', industry: 'Telecom', logoUrl: 'https://cdn.simpleicons.org/telefonica/0066FF', logoFallback: 'TEF', brandColor: '#0066FF', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'mixed', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'verizon', name: 'Verizon', ticker: 'VZ', sector: 'Communication Services', industry: 'Telecom', logoUrl: 'https://cdn.simpleicons.org/verizon/CD040B', logoFallback: 'VZ', brandColor: '#CD040B', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'mixed', governanceBand: 'strong', controversy: 'minor', newsSentiment: 'steady' },
  { id: 'deutsche-telekom', name: 'Deutsche Telekom', ticker: 'DTE', sector: 'Communication Services', industry: 'Telecom', logoUrl: 'https://cdn.simpleicons.org/t-mobile/E20074', logoFallback: 'DTE', brandColor: '#E20074', carbonIntensityBand: 'moderate', renewableTransitionBand: 'advancing', laborBand: 'stable', privacyBand: 'mixed', governanceBand: 'strong', controversy: 'none', newsSentiment: 'positive' },
];

export const dashboardBlueChipUniverse: DashboardCompany[] = dashboardBlueChipUniverseSource.slice(0, 50);

export const companyLogoDomains: Record<string, string> = {
  apple: 'apple.com',
  microsoft: 'microsoft.com',
  nvidia: 'nvidia.com',
  amazon: 'amazon.com',
  alphabet: 'google.com',
  meta: 'meta.com',
  netflix: 'netflix.com',
  tesla: 'tesla.com',
  oracle: 'oracle.com',
  salesforce: 'salesforce.com',
  sap: 'sap.com',
  ibm: 'ibm.com',
  tsmc: 'tsmc.com',
  asml: 'asml.com',
  samsung: 'samsung.com',
  sony: 'sony.com',
  alibaba: 'alibaba.com',
  tencent: 'tencent.com',
  siemens: 'siemens.com',
  airbus: 'airbus.com',
  'schneider-electric': 'se.com',
  honeywell: 'honeywell.com',
  caterpillar: 'caterpillar.com',
  toyota: 'toyota.com',
  byd: 'byd.com',
  shell: 'shell.com',
  bp: 'bp.com',
  totalenergies: 'totalenergies.com',
  nextera: 'nexteraenergy.com',
  enel: 'enel.com',
  jpmorgan: 'jpmorganchase.com',
  'goldman-sachs': 'goldmansachs.com',
  'bank-of-america': 'bankofamerica.com',
  hsbc: 'hsbc.com',
  ubs: 'ubs.com',
  visa: 'visa.com',
  mastercard: 'mastercard.com',
  'american-express': 'americanexpress.com',
  'berkshire-hathaway': 'berkshirehathaway.com',
  blackrock: 'blackrock.com',
  'novo-nordisk': 'novonordisk.com',
  roche: 'roche.com',
  'johnson-johnson': 'jnj.com',
  pfizer: 'pfizer.com',
  nestle: 'nestle.com',
  unilever: 'unilever.com',
  'procter-gamble': 'pg.com',
  pepsico: 'pepsico.com',
  'coca-cola': 'coca-cola.com',
  lvmh: 'lvmh.com',
  adyen: 'adyen.com',
  accenture: 'accenture.com',
  cisco: 'cisco.com',
  broadcom: 'broadcom.com',
  intel: 'intel.com',
  qualcomm: 'qualcomm.com',
  servicenow: 'servicenow.com',
  snowflake: 'snowflake.com',
  abb: 'abb.com',
  deere: 'deere.com',
  'rio-tinto': 'riotinto.com',
  bhp: 'bhp.com',
  linde: 'linde.com',
  suncor: 'suncor.com',
  novartis: 'novartis.com',
  merck: 'merck.com',
  sanofi: 'sanofi.com',
  telefonica: 'telefonica.com',
  verizon: 'verizon.com',
  'deutsche-telekom': 'telekom.com',
};
